### ISSUE TITLE
How is handled the case when a command is sent to an Order that doesn't exist?

### ISSUE THREAD

**Issue by ale64bit** [jgordijn/cqrs_template#1]
I'm failing to see how is handled the situation when a command is sent to an order that do not exists yet. I see that there's exception `UnknownOrderException` but I don't see when it's used. Moreover, since the `ShardRegion` will create new entries on demand (that is, if some entry id do not exist but a message is sent to an entry with such id, the entry will be created), it seems possible to create many new orders not associated with any users just by POSTing commands to the REST endpoint (for example, adding items).

**Comment by jgordijn** [comment]
Yes, you are right, great observation and thanks for letting us know. `UnknownOrderException` is never used. It is an artifact from a previous iteration.

We could change the business rule of an order so that it cannot items before it is created. We should then send an initialization command to the order. The order can decline all commands that are send before the initial command. This requires also feedback from order to orders, so that the orders only persist `OrderCreated` when the init command is processed by the order.

Another approach could be to make the route query to see if the order already exists and then decline the command if there is no such order. 

I think I would prefer the first solution. It might not really be pure CQRS, but with Akka it seems to be the most efficient implementation.

**Comment by ale64bit** [comment]
I agree with your first solution. I believe it won't be very hard, since you can just init the orders with some default uninitialized behavior (rejecting all commands) and sending the initialization message only from the `Orders` singleton (thus hot-swapping the order behavior via `become`). Also, after created, the orders can setup some receive timeout in order to stop themselves if not initialized within a reasonable threshold.
If interested, I can contribute with the change.

**Comment by jgordijn** [comment]
Absolutely, be my guest. I'm very interested in you contribution.

**Comment by jgordijn** [comment]
Fixed with https://github.com/jgordijn/cqrs_template/commit/f004eca91df55230c5c251b2ed45c76d673b73d7
